#FROM openjdk:17 AS appimage
#EXPOSE 8081
#WORKDIR /tmp
#COPY target/LibraryProject-0.0.1-SNAPSHOT.jar /tmp/LibraryProject-0.0.1-SNAPSHOT.jar
#ENTRYPOINT ["java","-jar","./LibraryProject-0.0.1-SNAPSHOT.jar"]
#
#FROM cassandra:latest AS databaseimage
#EXPOSE 9042
#COPY src/main/resources/library.cql home/library.cql
#CMD ["cqlsh","cassandra-docker-server","-f","/home/library.cql"]
#
#
#
#
